### Get my profile

GET http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImZpcnN0TmFtZSI6Illhbm5pY2siLCJhZ2UiOjEwMCwiZW1haWwiOiJ5YW5uaWNrQGdtYWlsLnRlc3QiLCJyb2xlIjoic3VwZXJfYWRtaW4iLCJpYXQiOjE3NTAzMzIxNzQsImV4cCI6MTc1MDQxODU3NH0.gbjd9H_WSEnqIzj2CvX02KPq1n5W5ssCsQhRXeAg9R4


### Get all the users

GET http://localhost:3000/api/users/all 








### Get all quizzes

GET http://localhost:3000/api/users/quiz/all








### Get the quiz generated

GET http://localhost:3000/api/users/quiz
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImZpcnN0TmFtZSI6IlN0YXBob3JkIiwiYWdlIjoxMCwiZW1haWwiOiJzdGFwaG9yZEBnbWFpbC50ZXN0IiwiaWF0IjoxNzQ4OTY1MTEyLCJleHAiOjE3NDkwNTE1MTJ9.WtM6CK-fjtguL-UgqbDP_zSAa1_-VjhJs769OWz9YZA





### Submit the quiz answers and get analysis

POST http://localhost:3000/api/users/quiz/5/answers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImZpcnN0TmFtZSI6IlN0YXBob3JkIiwiYWdlIjoxMCwiZW1haWwiOiJzdGFwaG9yZEBnbWFpbC50ZXN0IiwiaWF0IjoxNzQ4OTY1MTEyLCJleHAiOjE3NDkwNTE1MTJ9.WtM6CK-fjtguL-UgqbDP_zSAa1_-VjhJs769OWz9YZA

{
  "quizId": 5,
  "answers": [
    {"questionIndex": 0, "answers": "Building things and learning"},
    {"questionIndex": 1, "answers": "I lend a hand"},
    {"questionIndex": 2, "answers": "prefert learning something new by reading a book"},
    {"questionIndex": 3, "answers": "I feel proud"},
    {"questionIndex": 4, "answers": "I'd describe myself as a curious person, creative and determined"}
  ]
}


### Generate user profile outcome based on quiz answers and analysis
POST http://localhost:3000/api/users/quiz/5/generate-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImZpcnN0TmFtZSI6IlN0YXBob3JkIiwiYWdlIjoxMCwiZW1haWwiOiJzdGFwaG9yZEBnbWFpbC50ZXN0IiwiaWF0IjoxNzQ4OTY1MTEyLCJleHAiOjE3NDkwNTE1MTJ9.WtM6CK-fjtguL-UgqbDP_zSAa1_-VjhJs769OWz9YZA

{
  "quizId": 5,
 "answers": [
    {"questionIndex": 0, "answers": "Building things and learning"},
    {"questionIndex": 1, "answers": "I lend a hand"},
    {"questionIndex": 2, "answers": "prefert learning something new by reading a book"},
    {"questionIndex": 3, "answers": "I feel proud"},
    {"questionIndex": 4, "answers": "I'd describe myself as a curious person, creative and determined"}
  ]
}


### Generate educational content

POST http://localhost:3000/api/users/gen-educ-content
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImZpcnN0TmFtZSI6IlN0YXBob3JkIiwiYWdlIjoxMCwiZW1haWwiOiJzdGFwaG9yZEBnbWFpbC50ZXN0Iiwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE3NDk3NDQ2OTIsImV4cCI6MTc0OTgzMTA5Mn0.yjA8LQDpOCT2NUf9LMXs9MGrFYq0lRtyWRYmizCwaHU





### Check available gpt models

GET https://api.openai.com/v1/models
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImZpcnN0TmFtZSI6Ik5hcnV0byIsImFnZSI6MTAsImVtYWlsIjoibmFydXRvQGdtYWlsLmNvbSIsImlhdCI6MTc0NzIzMTA0MSwiZXhwIjoxNzQ3MzE3NDQxfQ.ur0ZBBYnIYvCwt6EXi8lDb1kmOHcM3ACtZTzslKBok8