### Get my profile

GET http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImZpcnN0TmFtZSI6IlN0YXBob3JkIiwiYWdlIjoxMCwiZW1haWwiOiJzdGFwaG9yZEBnbWFpbC50ZXN0IiwiaWF0IjoxNzQ4NjI4OTQ5LCJleHAiOjE3NDg3MTUzNDl9.Y6gOHdelaqLZW5mK9Q4-U71aiOUsUdi3EeL4r-EUA8Q


### Get all the users

GET http://localhost:3000/api/users/all 








### Get all quizzes

GET http://localhost:3000/api/users/quiz/all








### Get the quiz generated

GET http://localhost:3000/api/users/quiz
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImZpcnN0TmFtZSI6IlN0YXBob3JkIiwiYWdlIjoxMCwiZW1haWwiOiJzdGFwaG9yZEBnbWFpbC50ZXN0IiwiaWF0IjoxNzQ4NjI4OTQ5LCJleHAiOjE3NDg3MTUzNDl9.Y6gOHdelaqLZW5mK9Q4-U71aiOUsUdi3EeL4r-EUA8Q





### Submit the quiz answers and get analysis

POST http://localhost:3000/api/users/quiz/5/answers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImZpcnN0TmFtZSI6IlN0YXBob3JkIiwiYWdlIjoxMCwiZW1haWwiOiJzdGFwaG9yZEBnbWFpbC50ZXN0IiwiaWF0IjoxNzQ4NjI4OTQ5LCJleHAiOjE3NDg3MTUzNDl9.Y6gOHdelaqLZW5mK9Q4-U71aiOUsUdi3EeL4r-EUA8Q

{
  "quizId": 5,
  "answers": [
    {"questionIndex": 0, "answers": "Building things and learning"},
    {"questionIndex": 1, "answers": "I lend a hand"},
    {"questionIndex": 2, "answers": "prefert learning something new by reading a book"},
    {"questionIndex": 3, "answers": "I feel proud"},
    {"questionIndex": 4, "answers": "I'd describe myself as a curious person, creative and determined"}
  ]
}


### Generate user profile outcome based on quiz answers and analysis
POST http://localhost:3000/api/users/quiz/5/generate-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImZpcnN0TmFtZSI6IlN0YXBob3JkIiwiYWdlIjoxMCwiZW1haWwiOiJzdGFwaG9yZEBnbWFpbC50ZXN0IiwiaWF0IjoxNzQ4NjI4OTQ5LCJleHAiOjE3NDg3MTUzNDl9.Y6gOHdelaqLZW5mK9Q4-U71aiOUsUdi3EeL4r-EUA8Q

{
  "quizId": 5,
 "answers": [
    {"questionIndex": 0, "answers": "Building things and learning"},
    {"questionIndex": 1, "answers": "I lend a hand"},
    {"questionIndex": 2, "answers": "prefert learning something new by reading a book"},
    {"questionIndex": 3, "answers": "I feel proud"},
    {"questionIndex": 4, "answers": "I'd describe myself as a curious person, creative and determined"}
  ]
}







### Check available gpt models

GET https://api.openai.com/v1/models
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImZpcnN0TmFtZSI6Ik5hcnV0byIsImFnZSI6MTAsImVtYWlsIjoibmFydXRvQGdtYWlsLmNvbSIsImlhdCI6MTc0NzIzMTA0MSwiZXhwIjoxNzQ3MzE3NDQxfQ.ur0ZBBYnIYvCwt6EXi8lDb1kmOHcM3ACtZTzslKBok8