## Creating a student

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "firstName":"Staphord",
    "lastName":"Nkumbuye",
    "email":"staphord@gmail.test",
    "age":10,
    "role":"student",
    "password":"123456"
}

### Signin a student

POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "firstName":"Staphord",
    "password":"123456"
}
